/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AlumnoDAO;
import java.sql.Connection;
import modelo.Alumno;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author profe
 *
 * CRUD Create, Read, Update, Delete
 */
public class CrudAlumnos extends javax.swing.JFrame {
    
 

    private SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
  

    /**
     * Creates new form CrudAlumnos
     */
    public CrudAlumnos() {
        initComponents();
        //            
        this.setBounds(500, 500, 500, 500);
        setLocationRelativeTo(this);

      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFechaNac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCarrera = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaVisor = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 51, 255));
        jLabelTitulo.setText("CRUD DE ALUMNOS");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 150, 28));

        jLabel1.setText("Rut");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        getContentPane().add(jTextFieldRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 120, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 180, -1));

        jLabel3.setText("Fecha Nac:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        getContentPane().add(jTextFieldFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 120, -1));

        jLabel4.setText("Carrera");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        getContentPane().add(jTextFieldCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 200, -1));

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 80, -1));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 80, -1));

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 80, -1));

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 80, -1));

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 80, -1));

        jTextAreaVisor.setColumns(20);
        jTextAreaVisor.setRows(5);
        jScrollPane1.setViewportView(jTextAreaVisor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 410, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:

        //def variable locales
        String rut, nombre, carrera = "";
        Date fechaNac = null;

        try {

            rut = jTextFieldRut.getText();
            nombre = jTextFieldNombre.getText();
            try{
                fechaNac = formato.parse(jTextFieldFechaNac.getText());
            }catch(Exception e){
                System.out.println("Error en agregar fechaNac");
               fechaNac=null;
            }
            carrera = jTextFieldCarrera.getText();

            if(!rut.equals("") && !nombre.equals("") && fechaNac != null && !carrera.equals("")) {
                Alumno alumno = new Alumno(carrera, rut, nombre, fechaNac);

                if (AlumnoDAO.agregar(alumno) == true) {
                    JOptionPane.showMessageDialog(rootPane, "Bien, datos agregados...");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error, el rut ya existe...");
                }
                limpiar();
                
            } else {
                    JOptionPane.showMessageDialog(rootPane, "Error, los campos NO deben estar vacíos...");
            }

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_jButtonAgregarActionPerformed

    public void limpiar() {

        jTextFieldRut.setText("");
        jTextFieldNombre.setText("");
        jTextFieldFechaNac.setText("");
        jTextFieldCarrera.setText("");
    }


    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        // TODO add your handling code here:

        jTextAreaVisor.setText("");

        try {
            for (Alumno x : AlumnoDAO.obtenerDatos()) {

                jTextAreaVisor.append(x.toString() + "\n");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + ex.getMessage());
        }


    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:

        String rut = "";

        rut = jTextFieldRut.getText();

        Alumno alumno = null;
        try {
            alumno = AlumnoDAO.buscar(rut);
            System.out.println("boton buscar-> " + alumno);
        } catch (Exception ex) {
            Logger.getLogger(CrudAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (alumno != null) {
            jTextFieldNombre.setText(alumno.getNombre());
            jTextFieldFechaNac.setText(formato.format(alumno.getFechaNac()));
            jTextFieldCarrera.setText(alumno.getCarrera());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error, el rut no existe...");
        }


    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        String rut = "";

        rut = jTextFieldRut.getText();

        if (AlumnoDAO.eliminar(rut) == true) {
            JOptionPane.showMessageDialog(rootPane, "bien, datos eliminados...");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error, el rut no existe...");
        }
        limpiar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        //def variable locales
        String rut, nombre, carrera = "";
        Date fechaNac = null;

        try {
            rut = jTextFieldRut.getText();
            nombre = jTextFieldNombre.getText();
            fechaNac = formato.parse(jTextFieldFechaNac.getText());
            carrera = jTextFieldCarrera.getText();

            Alumno alumno = new Alumno(carrera, rut, nombre, fechaNac);

            if (AlumnoDAO.modificar(alumno) == true) {
                JOptionPane.showMessageDialog(rootPane, "Bien, datos modificados...");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error, el rut ya existe...");
            }

            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_jButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaVisor;
    private javax.swing.JTextField jTextFieldCarrera;
    private javax.swing.JTextField jTextFieldFechaNac;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldRut;
    // End of variables declaration//GEN-END:variables
}
